from project.controller import Controller

controller = Controller()

print(controller.add_aquarium("SaltwaterAquarium", 'AquaSalt'))
# print(controller.add_fish('AquaSalt', 'SaltwaterFish', 'Sea Bass', 'Bass', 20))
print(controller.add_aquarium("FreshwaterAquarium", 'Freshy'))
print(controller.add_fish("Freshy", 'FreshwaterFish', 'Sally', 'Salmon', 40))
print(controller.add_fish("Freshy", 'FreshwaterFish', 'Plessy', 'Fish', 20))
print(controller.add_fish("Freshy", 'asish', 'Plessy', 'Fish', 20))
print(controller.feed_fish('Freshy'))
print(controller.add_decoration('Ornament'))
print(controller.add_decoration('Ornament'))
print(controller.add_decoration('Plant'))
print(controller.add_decoration('Plant'))
print(controller.insert_decoration('Freshy', 'Ornament'))
print(controller.insert_decoration('Freshy', 'Plant'))
print(controller.insert_decoration('AquaSalt', 'Plant'))
print(controller.insert_decoration('AquaSalt', 'Ornament'))
print(controller.calculate_value('Freshy'))
print(controller.calculate_value('AquaSalt'))
print(controller.calculate_value('Alabala'))
print(controller.report())